### ISSUE TITLE
Completar tests automáticos

### ISSUE THREAD

**Issue by ignacioHermosilla** [ignacioHermosilla/transantiago-api#3]
Actualmente los tests automáticos cubren parcialmente la API. Además es necesario crear tests para las tareas críticas (servicio de predicción + servicio de posicionamiento de buses).

**Comment by cptchloroplast** [comment]
Hola Ignacio, encontré esta API el otro día y te quiero ayudar con su desarrollo.   Tienes un consejo dónde debería empezar? Gracias!

**Comment by ignacioHermosilla** [comment]
Genial, gracias! Voy a actualizar requirements.txt y agregar una pequeña sección de como correr el proyecto primero, para que sea más fácil desarrollar. Una vez hecho eso te cuento!
